# Q1 Testing orthogonal sets

In [3]:
import numpy as np

# gets dot product of 2 vectors v1, v2
def dot_product(v1, v2):
    sum = 0
    for i in range(len(v1)):
        sum += (v1[i] * v2[i])
    return sum

# checks whether vectors in set are orthogonal and prints out pairs which are not
def is_orthogonal(S):
    cols = S.T
    i, j, not_count = 0, 0, 0

    for i in range(len(cols) - 1):
        for j in range(i + 1, len(cols)):
            
            # calculate dot product of 2 vectors
            dp = dot_product(cols[i], cols[j])

            # if not 0, they're not orthogonal
            if not dp == 0:
                not_count += 1
                print("Vectors:", cols[i], "and", cols[j], "are not orthogonal")
        
    return not_count == 0

A = np.array([[-6, -3,  6,  1],
              [-1,  2,  1, -6],
              [ 3,  6,  3, -2],
              [ 6, -3,  6, -1],
              [ 2, -1,  2,  3],
              [-3,  6,  3,  2],
              [-2, -1,  2, -3],
              [ 1,  2,  1,  6]])


print("Columns in A are orthogonal" if is_orthogonal(A) else "Columns in A are not orthogonal")

Columns in A are orthogonal


### By definition, if the dot product of 2 vectors are 0, they are orthogonal. 
### The negation of which, if the dot product of 2 vectors are not 0, they must not be orthogonal.

# Q2 Orthonormalising a List L

In [4]:
# returns the normalised vector v
def normalise(v):
    return v / np.sqrt(dot_product(v, v))

# using GS process
def orthonormalise(L):
    L = L.T

    # new_L will hold orthonormal vectors v1 - vi
    new_L = L.copy()

    # skipping v1 because v1 = L1
    for i in range(1, len(L)):
        Li = L[i]
        for j in range(0, i):
            
            # projection of Li onto previous vectors
            top = dot_product(Li, new_L[j])
            bottom = dot_product(new_L[j], new_L[j])

            # in case dot product == 0, don't divide by 0
            if bottom == 0:
                Li *= 0
            else:
                sub = (top / bottom) * new_L[j]
                Li -= sub
        new_L[i] = Li
    
    return new_L.T

L = np.array([[4,  8, 10],
              [3,  9,  1],
              [1, -5, -1],
              [2, -5,  5]], dtype = "float")    

orthonormalise(L)

array([[ 4.        ,  2.13333333,  3.18548799],
       [ 3.        ,  4.6       , -3.94379152],
       [ 1.        , -6.46666667, -3.09351048],
       [ 2.        , -7.93333333,  1.09146653]])

# Q3 QR Factorisation

In [5]:
def qr_fac(A):

    # start QR as empty arrays
    Q, R = [], []
    
    # apply GS process on A
    v = orthonormalise(A.copy())

    # Q is a set of normalised columns of GS'd A
    for i in range(len(v.T)):
        vi = v.T[i]
        ei = normalise(vi)
        Q.append(ei)

        # row vector Ri, upper triangular matrix
        Ri = [0] * i

        # fill in Ri values, dot_product(ei, Aj)
        for j in range(i, len(v.T)):
            Aj = A.T[j]
            Rij = dot_product(ei, Aj)
            Ri.append(Rij)
        
        # adds row to R
        R.append(Ri)

    # convert to numpy arrays
    Q = np.array(Q, dtype = "float").T
    R = np.array(R, dtype = "float")

    return Q, R

L = np.array([[4,  8, 10],
              [3,  9,  1],
              [1, -5, -1],
              [2, -5,  5]], dtype = "float") 

Q, R = qr_fac(L)

print("L:\n", L, 
      "\n\nQ:\n", Q, 
      "\n\nR:\n", R, 
      "\n\nQxR:\n", np.matmul(Q, R))

L:
 [[ 4.  8. 10.]
 [ 3.  9.  1.]
 [ 1. -5. -1.]
 [ 2. -5.  5.]] 

Q:
 [[ 0.73029674  0.18677078  0.5275409 ]
 [ 0.54772256  0.4027245  -0.6531217 ]
 [ 0.18257419 -0.56614893 -0.51230873]
 [ 0.36514837 -0.69455384  0.18075511]] 

R:
 [[ 5.47722558  8.03326418  9.49385766]
 [ 0.         11.42220061 -0.63618797]
 [ 0.          0.          6.0383716 ]] 

QxR:
 [[ 4.  8. 10.]
 [ 3.  9.  1.]
 [ 1. -5. -1.]
 [ 2. -5.  5.]]
